AWSTemplateFormatVersion: '2010-09-09'
Resources:
  # DummyResource:
  #   Type: AWS::CloudFormation::WaitConditionHandle
  UserData:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: <image-id>
      InstanceType: <instace-type>
      KeyName: <keypair-name>
      Tags:
        - Key: Name
          Value: github-runner
      UserData:
        Fn::Base64: |
          #!/bin/bash
          set -x
          sudo yum update -y
          sudo yum install dotnet -y
          # Create a folder
          mkdir -p /home/ec2-user/actions-runner && cd /home/ec2-user/actions-runner
          # Download the latest runner package
          curl -o actions-runner-linux-x64-2.314.1.tar.gz -L https://github.com/actions/runner/releases/download/v2.314.1/actions-runner-linux-x64-2.314.1.tar.gz
          # Optional: Validate the hash
          # echo "6c726a118bbe02cd32e222f890e1e476567bf299353a96886ba75b423c1137b5  actions-runner-linux-x64-2.314.1.tar.gz" | shasum -a 256 -c
          # Extract the installer
          tar xzf ./actions-runner-linux-x64-2.314.1.tar.gz
          # Configure
          # Create the runner and start the configuration experience
          chown -R ec2-user:ec2-user /home/ec2-user/actions-runner
          # Use your runner token with in 1Hour otherwise it will expire
          sudo runuser -l ec2-user -c '/home/ec2-user/actions-runner/config.sh --url https://github.com/<user-name><repo-name> --token A25S2GF4APBZGYPDNCUHNE3GACI23 --name <runner-name>  --runnergroup default --labels <labels> --work default'
          # Last step, run it!
          # ./run.sh
          /home/ec2-user/actions-runner/svc.sh install
          /home/ec2-user/actions-runner/svc.sh start
          # Using your self-hosted runner
          # Use this YAML in your workflow file for each job
          # runs-on: self-hosted
